### ISSUE TITLE
ValueError: bad marshal data (unknown type code)

### ISSUE THREAD

**Issue by NguyenTuan-Dat** [yu-li/AGLLNet#1]
Hello yu-li,
I'm try using your AGLLNet but this issues raised on load model. I'm using Mac then Tensorflow==1.6.0 no above on pip.
Can you help me resolve this issues. Thanks you.
I'm using:
Tensorflow==2.5.0
Keras==2.4.3

```WARNING:tensorflow:From /Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "run_agllnet.py", line 70, in <module>
    run(INPUT_PATH, OUTPUT_PATH)
  File "run_agllnet.py", line 26, in run
    model = load_model('model/AgLLNet.h5')
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 201, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 180, in load_model_from_hdf5
    model = model_config_lib.model_from_config(model_config,
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/model_config.py", line 59, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 159, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 668, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2357, in from_config
    functional.reconstruct_from_config(config, custom_objects))
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1279, in reconstruct_from_config
    process_layer(layer_data)
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1261, in process_layer
    layer = deserialize_layer(layer_data, custom_objects=custom_objects)
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 159, in deserialize
    return generic_utils.deserialize_keras_object(
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 668, in deserialize_keras_object
    deserialized_obj = cls.from_config(
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1021, in from_config
    function = cls._parse_function_from_config(
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1073, in _parse_function_from_config
    function = generic_utils.func_load(
  File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 783, in func_load
    code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)```

**Comment by yu-li** [comment]
> Hello yu-li,
> I'm try using your AGLLNet but this issues raised on load model. I'm using Mac then Tensorflow==1.6.0 no above on pip.
> Can you help me resolve this issues. Thanks you.
> I'm using:
> Tensorflow==2.5.0
> Keras==2.4.3
> 
> ```
> Instructions for updating:
> non-resource variables are not supported in the long term
> Traceback (most recent call last):
>   File "run_agllnet.py", line 70, in <module>
>     run(INPUT_PATH, OUTPUT_PATH)
>   File "run_agllnet.py", line 26, in run
>     model = load_model('model/AgLLNet.h5')
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 201, in load_model
>     return hdf5_format.load_model_from_hdf5(filepath, custom_objects,
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 180, in load_model_from_hdf5
>     model = model_config_lib.model_from_config(model_config,
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/saving/model_config.py", line 59, in model_from_config
>     return deserialize(config, custom_objects=custom_objects)
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 159, in deserialize
>     return generic_utils.deserialize_keras_object(
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 668, in deserialize_keras_object
>     deserialized_obj = cls.from_config(
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/training.py", line 2357, in from_config
>     functional.reconstruct_from_config(config, custom_objects))
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1279, in reconstruct_from_config
>     process_layer(layer_data)
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/engine/functional.py", line 1261, in process_layer
>     layer = deserialize_layer(layer_data, custom_objects=custom_objects)
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/serialization.py", line 159, in deserialize
>     return generic_utils.deserialize_keras_object(
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 668, in deserialize_keras_object
>     deserialized_obj = cls.from_config(
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1021, in from_config
>     function = cls._parse_function_from_config(
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/layers/core.py", line 1073, in _parse_function_from_config
>     function = generic_utils.func_load(
>   File "/Users/ntdat/anaconda3/lib/python3.8/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 783, in func_load
>     code = marshal.loads(raw_code)
> ValueError: bad marshal data (unknown type code)```
> ```

Can you try a lower version of python? python3.5 works good for me.

**Comment by PINTO0309** [comment]
Python3.5
TensorFlow==1.12.0
Keras==2.1.6

success
![5047](https://user-images.githubusercontent.com/33194443/141605026-e5d89334-dc86-4b88-b12e-31d36a092554.png)
![5047](https://user-images.githubusercontent.com/33194443/141605027-a71d69fe-2c60-4e72-a325-7a905d902f3a.png)

https://github.com/keras-team/keras/issues/9595
